import type { Metadata } from "next";
import "./globals.css";
import {ReactNode} from "react";
import {Providers} from "@/app/providers";
import {ThemeSwitcher} from "@/components/theme-switcher/ThemeSwitcher";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <Providers>
          <div className='flex justify-end'>
              <ThemeSwitcher/>
          </div>
          {children}
      </Providers>
      </body>
    </html>
  );
}
